volumes:
  alert_service_postgres:
  alert_service_redis:
  pgadmin:
  redisinsight:

services:
  # alert_service:
  #   container_name: alert_service
  #   build:
  #     context: .
  #     dockerfile: ./backend/docker/local/alerts/Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - redis

  # bot_service:
  #   container_name: bot_service
  #   build:
  #     context: .
  #     dockerfile: ./backend/docker/local/bot/Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    container_name: alert_service_postgres
    image: postgres:16
    volumes:
      - alert_service_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

  redis:
    image: redis:6
    container_name: alert_service_redis
    command: ["/bin/sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    volumes:
      - alert_service_redis:/data
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env

  pgadmin:
    container_name: alert_pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./backend/.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  redisadmin:
    image: redis/redisinsight:latest
    container_name: alert_redisadmin
    depends_on:
      - redis
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
