"""create telegram and preferences table

Revision ID: 55325990a375
Revises: 
Create Date: 2025-03-02 17:14:15.242783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55325990a375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_start_time', sa.Time(), server_default='07:00', nullable=False),
    sa.Column('alert_end_time', sa.Time(), server_default='22:00', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['telegram.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_table('telegram')
    # ### end Alembic commands ###
