name: CI/CD

on:
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Use python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies and run linters
        run: |
          yarn --cwd ./frontend
          pip install pre-commit
          pre-commit install
          pre-commit run
